# Generated by Django 4.2.5 on 2023-10-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_remove_book_subject_book_image_url_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
