# Generated by Django 4.2.5 on 2023-10-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
