# Generated by Django 4.2.5 on 2023-10-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
        ('main', '0004_like_timestamp'),
    ]

    operations = [
    ]
